baseurl = "https://geojs.io"
languageCode = "en-AU"
title = "GeoJS Â· REST/JSON/JSONP GeoIP API"
theme = "kube"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-92272378-1"
# Build a robots.txt
enableRobotsTXT = true
# Don't do alias assets since Netlify handles that for us
disableAliases = true

description = "GeoJS is a highly available REST/JSON/JSONP IP Geolocation lookup API"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "paraiso-light"
# The monokai stylesheet is included in the base template.
#pygmentsUseClasses = true

[params]
RSSLink = "/index.xml"
author  = "jloh"
github  = "jloh"
twitter = "itsjloh"
email   = "contact@geojs.io"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -90
    url = "https://jloh.co/tag/geojs/"
##[[menu.main]]
##    name = "Live"
##    weight = -100
##    url = "/live/"

[outputs]
home = [ "HTML", "RSS", "REDIR", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
