baseurl = "https://www.geojs.io"
languageCode = "en-AU"
title = "GeoJS Â· REST/JSON/JSONP GeoIP API"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-92272378-1"
# Build a robots.txt
enableRobotsTXT = true
# Don't do alias assets since Netlify handles that for us
disableAliases = true

# Enable gitinfo
enableGitInfo = true

description = "GeoJS is a highly available REST/JSON/JSONP IP Geolocation lookup API"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false

[params]
RSSLink = "/index.xml"
author  = "jloh"
github  = "jloh"
twitter = "itsjloh"
email   = "contact@geojs.io"
repo    = "https://github.com/jloh/geojs-io"

[outputs]
home = [ "HTML", "RSS", "REDIRECTS", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
